# Generated by Django 5.2 on 2025-04-18 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_tag_place_category_userpreference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocation',
            old_name='last_updated',
            new_name='created_at',
        ),
    ]
