# Generated by Django 5.2 on 2025-04-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_place_location_place_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.TextField(default='Unknown'),
        ),
    ]
