# Generated by Django 5.2 on 2025-04-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_place_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
