# Generated by Django 5.2 on 2025-04-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('name', 'district')},
        ),
    ]
