# Generated by Django 5.2 on 2025-05-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_searchhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
