# Generated by Django 5.2 on 2025-06-08 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0015_place_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="crowddata",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="crowddata",
            name="time_slot",
            field=models.CharField(
                choices=[
                    ("morning", "Morning"),
                    ("afternoon", "Afternoon"),
                    ("evening", "Evening"),
                ],
                default="morning",
                max_length=10,
            ),
        ),
    ]
