# Generated by Django 5.2 on 2025-06-17 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_crowddata_date_crowddata_time_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowddata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='crowddata',
            name='time_slot',
        ),
    ]
