# Generated by Django 5.2 on 2025-06-17 03:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_crowddata_date_remove_crowddata_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowddata',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crowddata',
            name='time_slot',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=10),
        ),
    ]
