# Generated by Django 5.2 on 2025-06-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_crowddata_date_crowddata_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='district',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Lalitpur', 'Lalitpur'), ('Bhaktapur', 'Bhaktapur')], default='Kathmandu', max_length=100),
        ),
    ]
