# Generated by Django 5.2 on 2025-06-25 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_place_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.CreateModel(
            name='CrowdPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('crowdlevel', models.FloatField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.place')),
            ],
            options={
                'unique_together': {('place', 'hour')},
            },
        ),
    ]
