# Generated by Django 5.2 on 2025-06-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_place_district_crowdpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='fee_description',
            field=models.TextField(blank=True, help_text='Additional information about fees, discounts, or special conditions'),
        ),
        migrations.AddField(
            model_name='place',
            name='has_entry_fee',
            field=models.BooleanField(default=False, help_text='Whether this place has an entry fee'),
        ),
        migrations.AddField(
            model_name='place',
            name='local_fee_npr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entry fee for locals in NPR', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='saarc_fee_npr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entry fee for SAARC nationals in NPR', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tourist_fee_npr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entry fee for foreign tourists in NPR', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='tourist_fee_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entry fee for foreign tourists in USD', max_digits=6, null=True),
        ),
    ]
