# Generated by Django 5.2 on 2025-06-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_place_fee_description_place_has_entry_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='best_time_to_visit',
            field=models.CharField(blank=True, help_text='Best time to visit (e.g., Morning, Evening, Spring)', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='closed_dates',
            field=models.CharField(blank=True, help_text='Comma-separated dates or festival names when closed (e.g., 2025-10-24, Holi)', max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='Closing time (e.g., 17:00)', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='Opening time (e.g., 09:00)', null=True),
        ),
    ]
