# Generated by Django 5.2 on 2025-06-30 04:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_place_best_time_to_visit_place_closed_dates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowddata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(db_index=True, default='Travel', max_length=50),
        ),
        migrations.AlterField(
            model_name='place',
            name='district',
            field=models.CharField(db_index=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='search_query',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='search_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='crowddata',
            index=models.Index(fields=['place', 'timestamp'], name='backend_cro_place_i_1c87f9_idx'),
        ),
        migrations.AddIndex(
            model_name='crowddata',
            index=models.Index(fields=['timestamp'], name='backend_cro_timesta_8eaf3e_idx'),
        ),
        migrations.AddIndex(
            model_name='crowdpattern',
            index=models.Index(fields=['place', 'hour'], name='backend_cro_place_i_854e23_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['name', 'district'], name='backend_pla_name_ef5d77_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['category', 'district'], name='backend_pla_categor_790613_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_approved', 'district'], name='backend_pla_is_appr_74b092_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', 'timestamp'], name='backend_sea_user_id_02a93d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['search_type', 'timestamp'], name='backend_sea_search__9030fb_idx'),
        ),
    ]
